site_name: HyperProphet
theme:
  name: material

repo_name: hyperprophet/hyperprophet
repo_url: https://github.com/hyperprophet/hyperprophet
edit_uri: ""

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - HyperProphet: index.md
  - Quick Start: quick-start.md
  - Release Notes: release-notes.md